<a href="https://colab.research.google.com/github/WESAMAAM/SQL-for-Data-Analytics-Intermediate-Course/blob/main/Colab_SQL_Codes_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Colab SQL Codes Notebook

In [ ]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Connecting and switching to connection 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [ ]:
%%sql

-- View first 10 rows of sales to explore columns and data types
SELECT *
FROM sales
LIMIT 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
5,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
6,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00
7,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00
8,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16
9,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16

In [ ]:
%%sql

-- View first 10 rows of date table to understand calendar dimension fields
SELECT *
FROM date
LIMIT 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,date,datekey,year,yearquarter,yearquarternumber,quarter,yearmonth,yearmonthshort,yearmonthnumber,month,monthshort,monthnumber,dayofweek,dayofweekshort,dayofweeknumber,workingday,workingdaynumber
0,2015-01-01,20150101,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Thursday,Thu,5,0,0
1,2015-01-02,20150102,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Friday,Fri,6,1,1
2,2015-01-03,20150103,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Saturday,Sat,7,0,1
3,2015-01-04,20150104,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Sunday,Sun,1,0,1
4,2015-01-05,20150105,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Monday,Mon,2,1,2
5,2015-01-06,20150106,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Tuesday,Tue,3,1,3
6,2015-01-07,20150107,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Wednesday,Wed,4,1,4
7,2015-01-08,20150108,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Thursday,Thu,5,1,5
8,2015-01-09,20150109,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Friday,Fri,6,1,6
9,2015-01-10,20150110,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Saturday,Sat,7,0,6

In [ ]:
%%sql

-- View first 10 rows of store table to inspect branch locations and details
SELECT *
FROM store
LIMIT 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,storekey,storecode,geoareakey,countrycode,countryname,state,opendate,closedate,description,squaremeters,status
0,10,1,1,AU,Australia,Australian Capital Territory,2008-01-01,None,Contoso Store Australian Capital Territory,595.00,None
1,20,2,3,AU,Australia,Northern Territory,2008-01-12,2016-07-07,Contoso Store Northern Territory,665.00,Closed
2,30,3,5,AU,Australia,South Australia,2012-01-07,2015-08-08,Contoso Store South Australia,2000.00,Restructured
3,35,3,5,AU,Australia,South Australia,2015-12-08,None,Contoso Store South Australia,3000.00,None
4,40,4,6,AU,Australia,Tasmania,2010-01-01,None,Contoso Store Tasmania,2000.00,None
5,50,5,7,AU,Australia,Victoria,2015-12-09,None,Contoso Store Victoria,2000.00,None
6,60,6,8,AU,Australia,Western Australia,2010-01-01,None,Contoso Store Western Australia,2000.00,None
7,70,7,12,CA,Canada,New Brunswick,2007-05-07,2014-03-09,Contoso Store New Brunswick,1105.00,Restructured
8,72,7,12,CA,Canada,New Brunswick,2015-01-11,2018-02-02,Contoso Store New Brunswick,1500.00,Restructured
9,74,7,12,CA,Canada,New Brunswick,2018-06-02,None,Contoso Store New Brunswick,3500.00,None

In [ ]:
%%sql

-- View first 10 rows of customer table to see demographics and profile info
SELECT *
FROM customer
LIMIT 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customerkey,geoareakey,startdt,enddt,continent,gender,title,givenname,middleinitial,surname,...,zipcode,country,countryfull,birthday,age,occupation,company,vehicle,latitude,longitude
0,15,4,1990-09-10,2034-07-29,Australia,male,Mr.,Julian,A,McGuigan,...,4357,AU,Australia,1965-03-24,55,Border Patrol agent,Cut Rite Lawn Care,2000 Peugeot Kart Up,-27.83,151.17
1,23,8,1995-08-11,2045-01-26,Australia,female,Ms.,Rose,H,Dash,...,6055,AU,Australia,1990-05-10,30,Agricultural and food scientist,Rack N Sack,2005 Volvo XC90,-31.92,116.05
2,36,2,1992-03-12,2044-05-14,Australia,female,Ms.,Annabelle,J,Townsend,...,2304,AU,Australia,1964-07-16,56,Special education teacher,id Boutiques,1999 Lancia Lybra,-32.88,151.71
3,120,6,1983-07-23,2033-08-09,Australia,male,Mr.,Jamie,H,Hetherington,...,7256,AU,Australia,1946-12-11,74,Dental laboratory technician,Showbiz Pizza Place,2006 Dodge Durango,-39.77,144.02
4,180,7,1987-11-26,2026-10-14,Australia,male,Mr.,Gabriel,P,Bosanquet,...,3505,AU,Australia,1955-04-24,65,Administrative support specialist,Dubrow's Cafeteria,1995 Morgan Plus 4,-34.13,142.14
5,185,2,1990-08-01,2029-05-28,Australia,female,Mrs.,Gabrielle,B,Castella,...,2469,AU,Australia,1980-02-23,40,Management dietitian,d.e.m.o.,1997 Alpina B6,-29.01,152.84
6,189,7,2008-07-05,2017-11-01,Australia,female,Ms.,Hayley,C,Jull,...,3377,AU,Australia,1960-04-18,60,Sculptor,Asian Plan,2006 Alpina B5,-37.34,142.91
7,210,2,1980-09-28,2030-05-08,Australia,female,Mrs.,Natalie,L,Hilder,...,2632,AU,Australia,1950-11-23,70,Motel desk clerk,Enrich Garden Services,1995 Ford Fairlane,-36.84,149.05
8,225,7,1985-06-25,2017-09-25,Australia,male,Mr.,Hunter,J,Hutchins,...,3763,AU,Australia,1978-07-20,42,Teletype operator,Mr. Good Buys,2012 Lexus GX,-37.51,145.44
9,243,2,1982-02-07,2027-02-09,Australia,female,Ms.,Maya,J,Atherton,...,2446,AU,Australia,1954-05-15,66,Pilates instructor,Franklin Music,1995 Chevrolet Caprice,-31.36,152.39

In [ ]:
%%sql

-- View first 10 rows of product table to see categories, subcategories, and prices
SELECT *
FROM product
LIMIT 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,productkey,productcode,productname,manufacturer,brand,color,weightunit,weight,cost,price,categorykey,categoryname,subcategorykey,subcategoryname
0,1,101001,Contoso 512MB MP3 Player E51 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.80,6.62,12.99,1,Audio,101,MP4&MP3
1,2,101002,Contoso 512MB MP3 Player E51 Blue,"Contoso, Ltd",Contoso,Blue,ounces,4.10,6.62,12.99,1,Audio,101,MP4&MP3
2,3,101003,Contoso 1G MP3 Player E100 White,"Contoso, Ltd",Contoso,White,ounces,4.50,7.40,14.52,1,Audio,101,MP4&MP3
3,4,101004,Contoso 2G MP3 Player E200 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.50,11.00,21.57,1,Audio,101,MP4&MP3
4,5,101005,Contoso 2G MP3 Player E200 Red,"Contoso, Ltd",Contoso,Red,ounces,2.40,11.00,21.57,1,Audio,101,MP4&MP3
5,6,101006,Contoso 2G MP3 Player E200 Black,"Contoso, Ltd",Contoso,Black,ounces,8.80,11.00,21.57,1,Audio,101,MP4&MP3
6,7,101007,Contoso 2G MP3 Player E200 Blue,"Contoso, Ltd",Contoso,Blue,ounces,2.10,11.00,21.57,1,Audio,101,MP4&MP3
7,8,101008,Contoso 4G MP3 Player E400 Silver,"Contoso, Ltd",Contoso,Silver,ounces,5.60,30.58,59.99,1,Audio,101,MP4&MP3
8,9,101009,Contoso 4G MP3 Player E400 Black,"Contoso, Ltd",Contoso,Black,ounces,2.10,30.58,59.99,1,Audio,101,MP4&MP3
9,10,101010,Contoso 4G MP3 Player E400 Green,"Contoso, Ltd",Contoso,Green,ounces,11.00,30.58,59.99,1,Audio,101,MP4&MP3

In [ ]:
%%sql

-- View exchange rates used for converting different currencies
SELECT *
FROM currencyexchange
LIMIT 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

         date fromcurrency tocurrency  exchange
0  2015-01-01          AUD        AUD      1.00
1  2015-01-01          AUD        CAD      0.95
2  2015-01-01          AUD        EUR      0.67
3  2015-01-01          AUD        GBP      0.53
4  2015-01-01          AUD        USD      0.82
5  2015-01-01          CAD        AUD      1.05
6  2015-01-01          CAD        CAD      1.00
7  2015-01-01          CAD        EUR      0.71
8  2015-01-01          CAD        GBP      0.55
9  2015-01-01          CAD        USD      0.86

In [ ]:
%%sql

-- Categorize post-2020 sales as HIGH or LOW value based on total calculated net revenue
SELECT
  CASE WHEN sales.quantity * sales.netprice * sales.exchangerate >= 1000 THEN 'HIGH'
    ELSE 'LOW'
        END AS value,
customer.givenname,
customer.surname,
product.productname,
product.categoryname,
product.subcategoryname,
sales.orderdate,
sales.productkey,
sales.quantity,
sales.quantity * sales.netprice * sales.exchangerate AS multiqne
FROM sales

LEFT JOIN customer USING (customerkey)
LEFT JOIN product USING (productkey)

WHERE orderdate::date >= '2020/01/01'

LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,value,givenname,surname,productname,categoryname,subcategoryname,orderdate,productkey,quantity,multiqne
0,LOW,Heike,Burger,MGS Bicycle Card Games2009 E166,Games and Toys,Download Games,2020-01-01,1810,4,99.47
1,LOW,Heike,Burger,MGS Bicycle Board Games2009 E165,Games and Toys,Download Games,2020-01-01,1809,6,139.97
2,LOW,Heike,Burger,Proseware Wireless Photo All-in-One Printer M3...,Computers,"Printers, Scanners & Fax",2020-01-01,698,2,669.39
3,HIGH,Heike,Burger,Adventure Works Laptop12 M1200 Black,Computers,Laptops,2020-01-01,364,6,4090.60
4,LOW,Michelle,Seeber,Contoso Genuine Leather Grip Belt E322 Silver,Cameras and camcorders,Cameras & Camcorders Accessories,2020-01-01,1288,2,237.15
5,HIGH,Jason,Smith,Contoso Microwave 1.5CuFt X0110 Silver,Home Appliances,Microwaves,2020-01-01,2061,3,1507.16
6,LOW,Jason,Smith,MGS Flight Simulator X M250,Games and Toys,Download Games,2020-01-01,1717,3,189.35
7,LOW,Jason,Smith,Adventure Works Desktop PC1.60 ED160 White,Computers,Desktops,2020-01-01,435,1,539.90
8,HIGH,James,Frye,WWI Desktop PC2.30 M2300 Silver,Computers,Desktops,2020-01-01,451,5,5590.00
9,HIGH,Johnny,Couch,WWI LCD19W M100 White,Computers,Monitors,2020-01-01,535,10,3580.00

In [ ]:
%%sql

-- Calculate and format the total net revenue for sales from 2020 onwards
WITH nr AS
  (
  SELECT
  quantity * netprice * exchangerate AS multiqne
  FROM sales
  WHERE orderdate::date >= '2020/01/01'
  )

SELECT
TO_CHAR(SUM(nr.multiqne), 'FM999,999,999') AS netrevenue
FROM nr

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

    netrevenue
0  118,946,063

In [ ]:
%%sql

-- Count daily total customers and active customers by continent for the year 2023
SELECT
s.orderdate AS date,
COUNT(DISTINCT(s.customerkey)) AS total_customer,
COUNT(DISTINCT CASE WHEN c.continent = 'North America' THEN s.customerkey END ) AS na_customers,
COUNT(DISTINCT CASE WHEN c.continent = 'Europe' THEN s.customerkey END ) AS eu_customers,
COUNT(DISTINCT CASE WHEN c.continent = 'Australia' THEN s.customerkey END ) AS au_customers
FROM sales s

LEFT JOIN customer c USING (customerkey)

WHERE s.orderdate::date BETWEEN '2023/01/01' AND '2023/12/31'

GROUP BY s.orderdate

ORDER BY total_customer DESC

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

364 rows affected.

           date  total_customer  na_customers  eu_customers  au_customers
0    2023-02-18             157           100            47            10
1    2023-02-25             133            84            44             5
2    2023-02-22             122            74            45             3
3    2023-02-23             121            70            47             4
4    2023-02-16             121            73            37            11
..          ...             ...           ...           ...           ...
359  2023-04-23               4             1             3             0
360  2023-07-30               3             2             1             0
361  2023-03-26               2             2             0             0
362  2023-04-16               2             2             0             0
363  2023-04-02               1             1             0             0

[364 rows x 5 columns]

In [ ]:
%%sql

-- Compare the net revenue of each product category between 2022 and 2023
SELECT
    p.categoryname AS category,
    ROUND(SUM(s.netprice * s.quantity * s.exchangerate)::numeric, 0) AS net_revenue,
    TO_CHAR(SUM( CASE WHEN s.orderdate BETWEEN '2022/01/01' AND '2022/12/31' THEN s.netprice * s.quantity * s.exchangerate END), 'FM999,999,999') AS yr_2022,
    TO_CHAR(SUM( CASE WHEN s.orderdate BETWEEN '2023/01/01' AND '2023/12/31' THEN s.netprice * s.quantity * s.exchangerate END), 'FM999,999,999') AS yr_2023
FROM sales s

LEFT JOIN product p USING (productkey)

WHERE s.orderdate BETWEEN '2022/01/01' AND '2023/12/31'

GROUP BY p.categoryname

ORDER BY net_revenue DESC

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                        category net_revenue     yr_2022     yr_2023
0                      Computers    29513081  17,862,213  11,650,867
1                    Cell phones    14121813   8,119,665   6,002,148
2                Home Appliances    12532440   6,612,447   5,919,993
3                   TV and Video    10227515   5,815,337   4,412,178
4  Music, Movies and Audio Books     5170065   2,989,297   2,180,768
5        Cameras and camcorders      4366079   2,382,533   1,983,546
6                          Audio     1455628     766,938     688,690
7                 Games and Toys      586502     316,127     270,375

In [ ]:
%%sql

-- Compare average, max, and min sale amounts per product category for 2022 and 2023
SELECT
    p.categoryname AS category,
    ROUND(SUM(s.netprice * s.quantity * s.exchangerate)::numeric, 0) AS avg_revenue,
    AVG( CASE WHEN s.orderdate BETWEEN '2022/01/01' AND '2022/12/31' THEN s.netprice * s.quantity * s.exchangerate END) AS avg_2022,
    AVG( CASE WHEN s.orderdate BETWEEN '2023/01/01' AND '2023/12/31' THEN s.netprice * s.quantity * s.exchangerate END) AS avg_2023,
    TO_CHAR(MAX( CASE WHEN s.orderdate BETWEEN '2022/01/01' AND '2022/12/31' THEN s.netprice * s.quantity * s.exchangerate END), 'FM999,999,999') AS max_2022,
    TO_CHAR(MAX( CASE WHEN s.orderdate BETWEEN '2023/01/01' AND '2023/12/31' THEN s.netprice * s.quantity * s.exchangerate END), 'FM999,999,999') AS max_2023,
    MIN( CASE WHEN s.orderdate BETWEEN '2022/01/01' AND '2022/12/31' THEN s.netprice * s.quantity * s.exchangerate END) AS min_2022,
    MIN( CASE WHEN s.orderdate BETWEEN '2023/01/01' AND '2023/12/31' THEN s.netprice * s.quantity * s.exchangerate END) AS min_2023
FROM sales s

LEFT JOIN product p USING (productkey)

WHERE s.orderdate BETWEEN '2022/01/01' AND '2023/12/31'

GROUP BY p.categoryname

ORDER BY avg_revenue DESC

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,category,avg_revenue,avg_2022,avg_2023,max_2022,max_2023,min_2022,min_2023
0,Computers,29513081,1565.62,1292.39,"38,083","27,612",0.83,0.75
1,Cell phones,14121813,722.20,623.28,"7,692","8,912",2.53,2.28
2,Home Appliances,12532440,1755.36,1886.55,"31,655","32,916",4.04,4.54
3,TV and Video,10227515,1535.61,1687.90,"30,259","27,503",41.30,42.30
4,"Music, Movies and Audio Books",5170065,386.61,334.58,"5,415","3,805",7.29,6.91
5,Cameras and camcorders,4366079,1210.02,1210.96,"15,008","13,572",6.74,5.98
6,Audio,1455628,392.30,425.38,"3,473","2,731",9.31,10.85
7,Games and Toys,586502,81.29,80.83,"5,202","3,357",2.83,3.49

In [ ]:
%%sql

-- Find the median sales revenue per product category for the years 2022 and 2023
SELECT
    p.categoryname AS category,
    PERCENTILE_CONT(.5) WITHIN GROUP (ORDER BY (CASE WHEN s.orderdate BETWEEN '2022/01/01' AND '2022/12/31' THEN s.netprice * s.quantity * s.exchangerate END)) AS median_2022,
    PERCENTILE_CONT(.5) WITHIN GROUP (ORDER BY (CASE WHEN s.orderdate BETWEEN '2023/01/01' AND '2023/12/31' THEN s.netprice * s.quantity * s.exchangerate END)) AS median_2023
FROM sales s

LEFT JOIN product p USING (productkey)

WHERE s.orderdate BETWEEN '2022/01/01' AND '2023/12/31'

GROUP BY p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                        category  median_2022  median_2023
0                          Audio       257.21       266.59
1        Cameras and camcorders        651.46       672.60
2                    Cell phones       418.60       375.88
3                      Computers       809.70       657.18
4                 Games and Toys        33.78        32.62
5                Home Appliances       791.00       825.25
6  Music, Movies and Audio Books       186.58       159.63
7                   TV and Video       730.46       790.79

In [ ]:
%%sql

-- Calculate the overall median revenue across all sales records
SELECT
PERCENTILE_CONT(.5) WITHIN GROUP ( ORDER BY (quantity * netprice * exchangerate)) AS Median_revenue
FROM sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   median_revenue
0          399.17

In [ ]:
%%sql

-- Aggregate high vs low value revenue per category for 2022 and 2023 using the median as a threshold
SELECT
p.categoryname,
TO_CHAR(SUM(CASE WHEN s.orderdate::date BETWEEN '2022/01/01' AND '2022/12/31' AND s.quantity * s.netprice * s.exchangerate >= 399.17 THEN s.quantity * s.netprice * s.exchangerate END), 'FM999,999,999')
AS HIGH_REVENUE_2022,
TO_CHAR(SUM(CASE WHEN s.orderdate::date BETWEEN '2022/01/01' AND '2022/12/31' AND s.quantity * s.netprice * s.exchangerate < 399.17 THEN s.quantity * s.netprice * s.exchangerate END), 'FM999,999,999')
AS LOW_REVENUE_2022,
TO_CHAR(SUM(CASE WHEN s.orderdate::date BETWEEN '2023/01/01' AND '2023/12/31' AND s.quantity * s.netprice * s.exchangerate >= 399.17 THEN s.quantity * s.netprice * s.exchangerate END), 'FM999,999,999')
AS HIGH_REVENUE_2023,
TO_CHAR(SUM(CASE WHEN s.orderdate::date BETWEEN '2023/01/01' AND '2023/12/31' AND s.quantity * s.netprice * s.exchangerate < 399.17 THEN s.quantity * s.netprice * s.exchangerate END), 'FM999,999,999')
AS LOW_REVENUE_2023
FROM sales s

LEFT JOIN product p USING (productkey)

WHERE s.orderdate::date BETWEEN '2022/01/01' AND '2023/12/31'

GROUP BY p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,high_revenue_2022,low_revenue_2022,high_revenue_2023,low_revenue_2023
0,Audio,"543,006","223,933","506,843","181,847"
1,Cameras and camcorders,"2,248,731","133,801","1,878,278","105,269"
2,Cell phones,"7,296,455","823,210","5,263,290","738,858"
3,Computers,"17,235,481","626,733","11,058,482","592,385"
4,Games and Toys,"83,749","232,378","64,272","206,103"
5,Home Appliances,"6,392,251","220,196","5,742,934","177,059"
6,"Music, Movies and Audio Books","2,301,894","687,403","1,604,215","576,553"
7,TV and Video,"5,541,804","273,533","4,245,912","166,266"

In [ ]:
%%sql

-- Calculate the 25th, 50th (median), and 75th percentiles of overall transaction value
SELECT
PERCENTILE_CONT(.5) WITHIN GROUP ( ORDER BY (quantity * netprice * exchangerate)) AS per_50th,
PERCENTILE_CONT(.25) WITHIN GROUP ( ORDER BY (quantity * netprice * exchangerate)) AS per_25th,
PERCENTILE_CONT(.75) WITHIN GROUP ( ORDER BY (quantity * netprice * exchangerate)) AS per_75th
FROM sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   per_50th  per_25th  per_75th
0    399.17    105.40   1129.19

In [ ]:
%%sql

-- Classify and aggregate revenue for each category into low, median, and high tiers using percentiles
WITH per AS
(
  SELECT
  PERCENTILE_CONT(.25) WITHIN GROUP ( ORDER BY (quantity * netprice * exchangerate)) AS per_25th,
  PERCENTILE_CONT(.75) WITHIN GROUP ( ORDER BY (quantity * netprice * exchangerate)) AS per_75th
  FROM sales s

  WHERE orderdate::date BETWEEN '2022/01/01' AND '2023/12/31'
)

SELECT
  p.categoryname AS category,
  CASE WHEN (s.quantity * s.netprice * s.exchangerate) <= per.per_25th THEN 'LOW'
          WHEN (s.quantity * s.netprice * s.exchangerate) >= per.per_75th THEN 'HIGH'
              ELSE 'MEDIAN'
                  END AS tier,
  TO_CHAR(SUM(s.quantity * s.netprice * s.exchangerate), 'FM999,999,999') AS total_revenue
FROM sales s

LEFT JOIN product p USING (productkey)
CROSS JOIN per

WHERE orderdate::date BETWEEN '2022/01/01' AND '2023/12/31'

GROUP BY p.categoryname,
         tier

ORDER BY category

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

                         category    tier total_revenue
0                           Audio    HIGH       453,109
1                           Audio     LOW        49,819
2                           Audio  MEDIAN       952,700
3         Cameras and camcorders     HIGH     3,414,877
4         Cameras and camcorders      LOW        21,788
5         Cameras and camcorders   MEDIAN       929,414
6                     Cell phones    HIGH     8,557,889
7                     Cell phones     LOW       206,224
8                     Cell phones  MEDIAN     5,357,700
9                       Computers    HIGH    24,192,945
10                      Computers     LOW       114,336
11                      Computers  MEDIAN     5,205,799
12                 Games and Toys    HIGH        34,626
13                 Games and Toys     LOW       190,548
14                 Games and Toys  MEDIAN       361,328
15                Home Appliances    HIGH    10,851,234
16                Home Appliances     LOW        34,522
17                Home Appliances  MEDIAN     1,646,683
18  Music, Movies and Audio Books    HIGH     2,074,183
19  Music, Movies and Audio Books     LOW       278,524
20  Music, Movies and Audio Books  MEDIAN     2,817,359
21                   TV and Video    HIGH     8,406,607
22                   TV and Video     LOW        24,617
23                   TV and Video  MEDIAN     1,796,291

In [ ]:
%%sql

-- Calculate monthly total revenue and unique monthly customer counts
SELECT
  TO_CHAR(orderdate, 'YYYY/mm') AS orderdate_month,
  TO_CHAR(SUM(netprice * quantity * exchangerate), 'FM999,999,999') AS total_revenue,
  COUNT(DISTINCT customerkey) AS total_customers
FROM sales

GROUP BY orderdate_month

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

    orderdate_month total_revenue  total_customers
0           2015/01       384,093              200
1           2015/02       706,374              291
2           2015/03       332,962              139
3           2015/04       160,767               78
4           2015/05       548,633              236
..              ...           ...              ...
107         2023/12     2,928,551             1484
108         2024/01     2,677,499             1340
109         2024/02     3,542,323             1718
110         2024/03     1,692,855              877
111         2024/04       483,851              246

[112 rows x 3 columns]

In [ ]:
%%sql

-- Extract and aggregate total revenue breakdown by year and month
SELECT
  TO_CHAR(SUM(netprice * quantity * exchangerate), 'FM999,999,999') AS total_revenue,
  EXTRACT(YEAR FROM orderdate) AS orderdate_year,
  EXTRACT(MONTH FROM orderdate) AS orderdate_month
FROM sales

GROUP BY orderdate_year,
         orderdate_month

ORDER BY orderdate_year,
         orderdate_month

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

    total_revenue orderdate_year orderdate_month
0         384,093           2015               1
1         706,374           2015               2
2         332,962           2015               3
3         160,767           2015               4
4         548,633           2015               5
..            ...            ...             ...
107     2,928,551           2023              12
108     2,677,499           2024               1
109     3,542,323           2024               2
110     1,692,855           2024               3
111       483,851           2024               4

[112 rows x 3 columns]

In [ ]:
%%sql

-- Monitor daily product category revenues over the last 5 years relative to current date
SELECT
TO_CHAR(NOW(), 'YYYY/mm/dd') AS current_date,
TO_CHAR(s.orderdate, 'YYYY/mm/dd') AS orderdate,
p.categoryname,
SUM(s.netprice * s.quantity * s.exchangerate) AS total_revenue
FROM sales s

LEFT JOIN product p USING (productkey)

WHERE orderdate >= current_date - INTERVAL '5 years'

GROUP BY orderdate,
         p.categoryname

ORDER BY orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

7129 rows affected.

     current_date   orderdate                   categoryname  total_revenue
0      2026/10/01  2021/10/01                          Audio        3124.93
1      2026/10/01  2021/10/01        Cameras and camcorders         4916.13
2      2026/10/01  2021/10/01                    Cell phones       15482.64
3      2026/10/01  2021/10/01                      Computers       17700.37
4      2026/10/01  2021/10/01                 Games and Toys         717.69
...           ...         ...                            ...            ...
7124   2026/10/01  2024/04/20                      Computers       58353.68
7125   2026/10/01  2024/04/20                 Games and Toys        1744.30
7126   2026/10/01  2024/04/20                Home Appliances        1562.04
7127   2026/10/01  2024/04/20  Music, Movies and Audio Books        4949.43
7128   2026/10/01  2024/04/20                   TV and Video        9841.91

[7129 rows x 4 columns]

In [ ]:
%%sql

-- Measure order processing times (delivery date minus order date) and annual revenue
SELECT
  EXTRACT(YEAR FROM orderdate) AS order_year,
  ROUND(AVG(EXTRACT(DAY FROM AGE(deliverydate, orderdate))), 2) AS avg_processing_time,
  PERCENTILE_CONT(.5) WITHIN GROUP ( ORDER BY (EXTRACT(DAY FROM AGE(deliverydate, orderdate)))) AS median_processing_time,
  TO_CHAR(SUM(netprice * quantity * exchangerate), 'FM999,999,999') AS multinqe
FROM sales

GROUP BY order_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

  order_year avg_processing_time  median_processing_time    multinqe
0       2015                1.10                    0.00   7,370,979
1       2016                1.08                    0.00  10,383,614
2       2017                0.83                    0.00  13,221,339
3       2018                0.86                    0.00  24,667,448
4       2019                0.81                    0.00  31,818,096
5       2020                0.93                    0.00  11,218,436
6       2021                1.36                    0.00  21,357,977
7       2022                1.62                    1.00  44,864,557
8       2023                1.75                    2.00  33,108,566
9       2024                1.67                    1.00   8,396,527

In [ ]:
%%sql

-- Determine the daily revenue contribution percentage of each line number partition
WITH n_r AS
(
  SELECT
  linenumber,
  orderdate,
  SUM(netprice * quantity * exchangerate) OVER(PARTITION BY linenumber, orderdate::date) AS net_revenue,
  SUM(netprice * quantity * exchangerate) OVER(PARTITION BY orderdate::date) AS daily_net_revenue
  FROM sales
)

SELECT *,
net_revenue / daily_net_revenue * 100  AS pct_daily_net_revenue
FROM n_r

ORDER BY orderdate,
         linenumber

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

50 rows affected.

,linenumber,orderdate,net_revenue,daily_net_revenue,pct_daily_net_revenue
0,0,2015-01-01,3235.92,11640.80,27.80
1,0,2015-01-01,3235.92,11640.80,27.80
2,0,2015-01-01,3235.92,11640.80,27.80
3,0,2015-01-01,3235.92,11640.80,27.80
4,0,2015-01-01,3235.92,11640.80,27.80
5,0,2015-01-01,3235.92,11640.80,27.80
6,0,2015-01-01,3235.92,11640.80,27.80
7,0,2015-01-01,3235.92,11640.80,27.80
8,0,2015-01-01,3235.92,11640.80,27.80
9,1,2015-01-01,4096.03,11640.80,35.19
10,1,2015-01-01,4096.03,11640.80,35.19
11,1,2015-01-01,4096.03,11640.80,35.19
12,1,2015-01-01,4096.03,11640.80,35.19
13,1,2015-01-01,4096.03,11640.80,35.19
14,1,2015-01-01,4096.03,11640.80,35.19
15,1,2015-01-01,4096.03,11640.80,35.19
16,2,2015-01-01,1607.47,11640.80,13.81
17,2,2015-01-01,1607.47,11640.80,13.81
18,2,2015-01-01,1607.47,11640.80,13.81
19,2,2015-01-01,1607.47,11640.80,13.81
20,3,2015-01-01,2596.25,11640.80,22.30
21,3,2015-01-01,2596.25,11640.80,22.30
22,3,2015-01-01,2596.25,11640.80,22.30
23,4,2015-01-01,67.61,11640.80,0.58
24,5,2015-01-01,37.51,11640.80,0.32
25,0,2015-01-02,3849.15,5890.40,65.35
26,0,2015-01-02,3849.15,5890.40,65.35
27,0,2015-01-02,3849.15,5890.40,65.35
28,0,2015-01-02,3849.15,5890.40,65.35
29,0,2015-01-02,3849.15,5890.40,65.35
30,0,2015-01-02,3849.15,5890.40,65.35
31,1,2015-01-02,2041.25,5890.40,34.65
32,1,2015-01-02,2041.25,5890.40,34.65
33,0,2015-01-03,4760.69,19796.67,24.05
34,0,2015-01-03,4760.69,19796.67,24.05
35,0,2015-01-03,4760.69,19796.67,24.05
36,0,2015-01-03,4760.69,19796.67,24.05
37,0,2015-01-03,4760.69,19796.67,24.05
38,0,2015-01-03,4760.69,19796.67,24.05
39,0,2015-01-03,4760.69,19796.67,24.05
40,0,2015-01-03,4760.69,19796.67,24.05
41,0,2015-01-03,4760.69,19796.67,24.05
42,0,2015-01-03,4760.69,19796.67,24.05
43,0,2015-01-03,4760.69,19796.67,24.05
44,1,2015-01-03,10691.06,19796.67,54.00
45,1,2015-01-03,10691.06,19796.67,54.00
46,1,2015-01-03,10691.06,19796.67,54.00
47,1,2015-01-03,10691.06,19796.67,54.00
48,1,2015-01-03,10691.06,19796.67,54.00
49,1,2015-01-03,10691.06,19796.67,54.00

In [ ]:
%%sql

-- Cohort Analysis: Track annual net revenue generated by customer cohorts grouped by their joining year
  WITH y_c AS
  (
    SELECT DISTINCT
    customerkey,
    EXTRACT(YEAR FROM MIN(orderdate) OVER(PARTITION BY customerkey)) AS cohort_date
    FROM sales
  )

SELECT
  EXTRACT(YEAR FROM orderdate::date) AS year_date,
  cohort_date,
  TO_CHAR(SUM(netprice * quantity * exchangerate), 'FM999,999,999') AS net_revenue
FROM sales

LEFT JOIN y_c USING (customerkey)

GROUP BY cohort_date,
         EXTRACT(YEAR FROM orderdate::date)

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

50 rows affected.

   year_date cohort_date net_revenue
0       2015        2015   7,370,979
1       2016        2015     392,623
2       2017        2015     479,841
3       2018        2015   1,069,851
4       2019        2015   1,235,991
5       2020        2015     386,490
6       2021        2015     872,846
7       2022        2015   1,569,788
8       2023        2015   1,157,634
9       2024        2015     356,187
10      2016        2016   9,990,990
11      2017        2016     497,028
12      2018        2016   1,074,607
13      2019        2016   1,565,401
14      2020        2016     474,087
15      2021        2016     964,418
16      2022        2016   2,164,681
17      2023        2016   1,265,243
18      2024        2016     364,067
19      2017        2017  12,244,470
20      2018        2017   1,407,065
21      2019        2017   1,764,717
22      2020        2017     625,928
23      2021        2017   1,329,859
24      2022        2017   2,428,883
25      2023        2017   1,714,010
26      2024        2017     464,803
27      2018        2018  21,115,925
28      2019        2018   3,229,188
29      2020        2018   1,171,127
30      2021        2018   2,201,262
31      2022        2018   4,534,296
32      2023        2018   3,271,754
33      2024        2018     936,834
34      2019        2019  24,022,799
35      2020        2019   1,295,045
36      2021        2019   2,337,595
37      2022        2019   4,848,981
38      2023        2019   3,440,099
39      2024        2019     751,726
40      2020        2020   7,265,759
41      2021        2020   1,016,399
42      2022        2020   1,891,708
43      2023        2020   1,435,051
44      2024        2020     312,983
45      2021        2021  12,635,598
46      2022        2021   3,014,083
47      2023        2021   2,242,370
48      2024        2021     495,686
49      2022        2022  24,412,138

In [ ]:
%%sql

-- Compare individual customer lifetime value (LTV) against the average LTV of their registration cohort year
WITH y_c AS
(
    SELECT
        customerkey,
        EXTRACT(YEAR FROM MIN(orderdate)) AS cohort_date,
        SUM(netprice * quantity * exchangerate) AS customer_ltv
    FROM sales

    GROUP BY customerkey
)

SELECT
    *,
    AVG(customer_ltv) OVER(PARTITION BY cohort_date) AS avg_cohort_ltv
FROM y_c

ORDER BY customerkey

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

50 rows affected.

    customerkey cohort_date  customer_ltv  avg_cohort_ltv
0            15        2021       2217.41         3943.33
1           180        2018       2510.22         4896.64
2           185        2019       1395.52         4731.95
3           243        2016        287.67         5404.92
4           387        2018       4655.84         4896.64
5           406        2021       2193.42         3943.33
6           545        2023       3551.47         2543.18
7           649        2022       4063.09         3315.52
8           668        2019        162.29         4731.95
9           688        2023      16909.04         2543.18
10          864        2019      11367.19         4731.95
11          957        2018       5515.44         4896.64
12          963        2023         46.99         2543.18
13         1045        2022       4766.08         3315.52
14         1092        2019        673.49         4731.95
15         1194        2019      13472.82         4731.95
16         1358        2023        425.51         2543.18
17         1371        2016       2151.03         5404.92
18         1381        2020       4296.61         3933.32
19         1401        2024        405.85         2037.55
20         1509        2016       1247.62         5404.92
21         1539        2021       2216.74         3943.33
22         1583        2022        738.06         3315.52
23         1802        2022       5290.79         3315.52
24         1806        2022        808.58         3315.52
25         1807        2022        262.75         3315.52
26         1898        2023        606.32         2543.18
27         2185        2021       9492.66         3943.33
28         2267        2018        904.90         4896.64
29         2268        2023       1243.54         2543.18
30         2283        2023         70.80         2543.18
31         2439        2019         40.44         4731.95
32         2523        2018       6985.49         4896.64
33         2599        2021       8608.97         3943.33
34         2608        2022       8465.10         3315.52
35         2622        2024        550.77         2037.55
36         2659        2017        729.92         5403.08
37         2661        2022        113.25         3315.52
38         2704        2018       7536.59         4896.64
39         2752        2017       2022.93         5403.08
40         2793        2019      14456.60         4731.95
41         2833        2019        189.80         4731.95
42         2863        2018        102.20         4896.64
43         2962        2024       1494.11         2037.55
44         2986        2018       8619.97         4896.64
45         3008        2023       2260.06         2543.18
46         3011        2022       1166.12         3315.52
47         3012        2016       6712.90         5404.92
48         3077        2017      20633.44         5403.08
49         3081        2021      15586.82         3943.33

In [ ]:
%%sql

-- Compute the rolling average order value and lifetime order count for each customer over time
SELECT
  customerkey,
  orderdate,
  netprice * quantity * exchangerate AS net_revenue,
  AVG(netprice * quantity * exchangerate) OVER(
                                                PARTITION BY customerkey
                                                ORDER BY orderdate
                                              ) AS running_order_avg,
                                 COUNT(*) OVER(
                                                PARTITION BY customerkey
                                                ORDER BY orderdate
                                              ) AS running_order_count
FROM sales

ORDER BY customerkey

LIMIT 50

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

50 rows affected.

,customerkey,orderdate,net_revenue,running_order_avg,running_order_count
0,15,2021-03-08,2217.41,2217.41,1
1,180,2018-07-28,525.31,525.31,1
2,180,2023-08-28,1913.55,836.74,3
3,180,2023-08-28,71.36,836.74,3
4,185,2019-06-01,1395.52,1395.52,1
5,243,2016-05-19,287.67,287.67,1
6,387,2018-12-21,97.05,592.64,4
7,387,2018-12-21,1608.10,592.64,4
8,387,2018-12-21,619.77,592.64,4
9,387,2018-12-21,45.62,592.64,4
10,387,2021-10-30,1265.56,727.22,5
11,387,2023-11-16,362.44,517.32,9
12,387,2023-11-16,446.44,517.32,9
13,387,2023-11-16,180.35,517.32,9
14,387,2023-11-16,30.51,517.32,9
15,406,2021-11-06,762.69,1096.71,2
16,406,2021-11-06,1430.73,1096.71,2
17,545,2023-07-01,1475.91,591.91,6
18,545,2023-07-01,66.40,591.91,6
19,545,2023-07-01,266.21,591.91,6
20,545,2023-07-01,79.67,591.91,6
21,545,2023-07-01,318.67,591.91,6
22,545,2023-07-01,1344.62,591.91,6
23,649,2022-05-16,370.53,578.49,4
24,649,2022-05-16,599.46,578.49,4
25,649,2022-05-16,1083.96,578.49,4
26,649,2022-05-16,260.03,578.49,4
27,649,2023-05-22,1179.11,677.18,6
28,649,2023-05-22,570.00,677.18,6
29,668,2019-10-01,162.29,162.29,1
30,688,2023-09-13,1337.72,3381.81,5
31,688,2023-09-13,905.77,3381.81,5
32,688,2023-09-13,2473.78,3381.81,5
33,688,2023-09-13,85.24,3381.81,5
34,688,2023-09-13,12106.53,3381.81,5
35,864,2019-01-22,848.18,848.18,1
36,864,2020-01-15,39.94,444.06,2
37,864,2022-07-09,10479.07,3789.06,3
38,957,2018-11-08,567.12,567.12,1
39,957,2022-02-24,4213.51,2390.32,2
40,957,2022-09-26,734.80,1838.48,3
41,963,2023-12-21,46.99,46.99,1
42,1045,2022-06-25,148.66,307.20,2
43,1045,2022-06-25,465.75,307.20,2
44,1045,2023-03-02,4098.16,1191.52,4
45,1045,2023-03-02,53.52,1191.52,4
46,1092,2019-11-07,276.73,276.73,1
47,1092,2024-02-14,396.76,336.75,2
48,1194,2019-05-20,4335.39,3320.51,4
49,1194,2019-05-20,136.30,3320.51,4

In [ ]:
%%sql

-- Compare ROW_NUMBER, RANK, and DENSE_RANK ranking results based on customer total order volumes
SELECT
  customerkey,
  COUNT(*) AS total_orders,
  ROW_NUMBER() OVER (ORDER BY COUNT(*) DESC ) AS total_orders_row_num,
  RANK() OVER (ORDER BY COUNT(*) DESC ) AS total_orders_rank,
  DENSE_RANK() OVER (ORDER BY COUNT(*) DESC ) AS total_orders_dense_rank
FROM sales

GROUP BY customerkey
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customerkey,total_orders,total_orders_row_num,total_orders_rank,total_orders_dense_rank
0,1834524,31,1,1,1
1,1375597,30,2,2,2
2,249557,27,3,3,3
3,1495941,26,4,4,4
4,459519,26,5,4,4
5,1801215,26,6,4,4
6,1219056,25,7,7,5
7,1876222,24,8,8,6
8,1427444,24,9,8,6
9,759419,24,10,8,6

In [ ]:
%%sql

-- Calculate month-on-month growth rate and raw difference in monthly revenue during 2023
WITH monthly_revenue AS
(
  SELECT
    TO_CHAR(orderdate, 'yyyy/mm') AS date,
    SUM(netprice * quantity * exchangerate) AS net_revenue
  FROM sales

  WHERE EXTRACT(YEAR FROM orderdate) = 2023

  GROUP BY date

  ORDER BY date
)

SELECT
  *,
  LAG(net_revenue) OVER(ORDER BY date) AS p_month_revenue,
  net_revenue - LAG(net_revenue) OVER(ORDER BY date) AS monthly_rev_grouth,
  100 * (net_revenue - LAG(net_revenue) OVER(ORDER BY date)) / LAG(net_revenue) OVER(ORDER BY date) AS rate
FROM monthly_revenue

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

       date  net_revenue  p_month_revenue  monthly_rev_grouth   rate
0   2023/01   3664431.34              NaN                 NaN    NaN
1   2023/02   4465204.57       3664431.34           800773.22  21.85
2   2023/03   2244316.52       4465204.57         -2220888.05 -49.74
3   2023/04   1162796.16       2244316.52         -1081520.36 -48.19
4   2023/05   2943005.99       1162796.16          1780209.83 153.10
5   2023/06   2864500.03       2943005.99           -78505.96  -2.67
6   2023/07   2337639.34       2864500.03          -526860.69 -18.39
7   2023/08   2623919.79       2337639.34           286280.45  12.25
8   2023/09   2622774.85       2623919.79            -1144.94  -0.04
9   2023/10   2551322.61       2622774.85           -71452.24  -2.72
10  2023/11   2700103.38       2551322.61           148780.78   5.83
11  2023/12   2928550.93       2700103.38           228447.54   8.46

In [ ]:
%%sql

-- Compare the year-over-year rate of change for average LTV across different annual customer cohorts
WITH c_n AS
  (
    SELECT
      customerkey,
      EXTRACT(YEAR FROM (MIN(orderdate))) AS cohort_year,
      SUM(netprice * quantity * exchangerate) AS customer_ltv
    FROM sales

    GROUP BY customerkey
  ),

cohort_summary AS
  (
    SELECT
      cohort_year,
      customerkey,
      AVG(customer_ltv) OVER(PARTITION BY cohort_year) AS avg_cohort_ltv
    FROM c_n
    ORDER BY cohort_year
  ),

  cohort_final AS
  (
    SELECT DISTINCT
      cohort_year,
      avg_cohort_ltv
    FROM cohort_summary

    ORDER BY cohort_year
  )

  SELECT *,
    LAG(avg_cohort_ltv) OVER(ORDER BY cohort_year) AS p_ltv,
    avg_cohort_ltv - LAG(avg_cohort_ltv) OVER(ORDER BY cohort_year) AS change,
    100 * (avg_cohort_ltv - LAG(avg_cohort_ltv) OVER(ORDER BY cohort_year)) / avg_cohort_ltv AS rate
  FROM cohort_final

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

  cohort_year  avg_cohort_ltv   p_ltv  change   rate
0        2015         5271.59     NaN     NaN    NaN
1        2016         5404.92 5271.59  133.34   2.47
2        2017         5403.08 5404.92   -1.84  -0.03
3        2018         4896.64 5403.08 -506.44 -10.34
4        2019         4731.95 4896.64 -164.69  -3.48
5        2020         3933.32 4731.95 -798.62 -20.30
6        2021         3943.33 3933.32   10.00   0.25
7        2022         3315.52 3943.33 -627.81 -18.94
8        2023         2543.18 3315.52 -772.34 -30.37
9        2024         2037.55 2543.18 -505.63 -24.82

In [ ]:
%%sql

-- Compute a 3-month moving average of monthly revenues for the year 2023
 WITH m_r  AS
 (
  SELECT
      TO_CHAR(orderdate, 'yyyy/mm') AS date,
      SUM(netprice * quantity * exchangerate) AS net_revenue
    FROM sales

    WHERE EXTRACT(YEAR FROM orderdate) = 2023

    GROUP BY date

    ORDER BY date
 ),

final AS
 (
  SELECT
    date,
    net_revenue,
    AVG(net_revenue) OVER(ORDER BY date ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING)
  FROM m_r
 )

 SELECT *
 FROM final

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

       date  net_revenue        avg
0   2023/01   3664431.34 4064817.96
1   2023/02   4465204.57 3457984.14
2   2023/03   2244316.52 2624105.75
3   2023/04   1162796.16 2116706.22
4   2023/05   2943005.99 2323434.06
5   2023/06   2864500.03 2715048.45
6   2023/07   2337639.34 2608686.39
7   2023/08   2623919.79 2528111.33
8   2023/09   2622774.85 2599339.08
9   2023/10   2551322.61 2624733.61
10  2023/11   2700103.38 2726658.97
11  2023/12   2928550.93 2814327.15